import type { Artifact } from '@/lib/artifacts';

export const SHIPPED_PREFABS: Artifact[] = [
  {
    id: 'prefab_arcology_base',
    name: 'Arcology Base',
    type: 'prefab',
    tags: ["structure","glitch"],
    anchor: [-17,0,-15],
    cells: [
      { dx: -3, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: -3, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: -3, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: -3, dy: 0, dz: 3, blockId: 'circuit', layer: 0 },
      { dx: -2, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: -1, blockId: 'circuit', layer: 0 },
      { dx: 3, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_arcology_core',
    name: 'Arcology Core',
    type: 'prefab',
    tags: ["structure","neon","glitch"],
    anchor: [0,5,-12],
    cells: [
      { dx: -3, dy: 0, dz: -3, blockId: 'corp-glass', layer: 5 },
      { dx: -3, dy: 0, dz: 1, blockId: 'corp-glass', layer: 5 },
      { dx: -2, dy: 0, dz: 3, blockId: 'corp-glass', layer: 5 },
      { dx: 0, dy: 0, dz: 3, blockId: 'corp-glass', layer: 5 },
      { dx: 2, dy: 0, dz: 3, blockId: 'corp-glass', layer: 5 },
      { dx: 3, dy: 0, dz: 0, blockId: 'corp-glass', layer: 5 },
      { dx: -3, dy: 1, dz: -3, blockId: 'corp-glass', layer: 6 },
      { dx: -3, dy: 1, dz: 1, blockId: 'corp-glass', layer: 6 },
      { dx: -2, dy: 1, dz: 3, blockId: 'corp-glass', layer: 6 },
      { dx: 0, dy: 1, dz: 3, blockId: 'corp-glass', layer: 6 },
      { dx: 2, dy: 1, dz: 3, blockId: 'corp-glass', layer: 6 },
      { dx: 3, dy: 1, dz: 0, blockId: 'corp-glass', layer: 6 },
      { dx: -3, dy: 2, dz: -3, blockId: 'corp-glass', layer: 7 },
      { dx: -3, dy: 2, dz: 1, blockId: 'corp-glass', layer: 7 },
      { dx: -2, dy: 2, dz: 3, blockId: 'corp-glass', layer: 7 },
      { dx: 0, dy: 2, dz: 3, blockId: 'corp-glass', layer: 7 },
      { dx: 2, dy: 2, dz: 3, blockId: 'corp-glass', layer: 7 },
      { dx: 3, dy: 2, dz: 0, blockId: 'corp-glass', layer: 7 },
      { dx: -3, dy: 3, dz: -3, blockId: 'neon-cyan', layer: 8 },
      { dx: -3, dy: 3, dz: 1, blockId: 'neon-cyan', layer: 8 },
      { dx: -2, dy: 3, dz: -2, blockId: 'neon-cyan', layer: 8 },
      { dx: -2, dy: 3, dz: 2, blockId: 'neon-cyan', layer: 8 },
      { dx: -1, dy: 3, dz: -1, blockId: 'neon-cyan', layer: 8 },
      { dx: -1, dy: 3, dz: 3, blockId: 'neon-cyan', layer: 8 },
      { dx: 0, dy: 3, dz: 0, blockId: 'neon-cyan', layer: 8 },
      { dx: 1, dy: 3, dz: -3, blockId: 'neon-cyan', layer: 8 },
      { dx: 1, dy: 3, dz: 1, blockId: 'neon-cyan', layer: 8 },
      { dx: 2, dy: 3, dz: -2, blockId: 'neon-cyan', layer: 8 },
      { dx: 2, dy: 3, dz: 2, blockId: 'neon-cyan', layer: 8 },
      { dx: 3, dy: 3, dz: -1, blockId: 'neon-cyan', layer: 8 },
      { dx: 3, dy: 3, dz: 3, blockId: 'neon-cyan', layer: 8 },
      { dx: 0, dy: 1, dz: 2, blockId: 'circuit', layer: 6 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_arcology_crown',
    name: 'Arcology Crown',
    type: 'prefab',
    tags: ["structure","neon","data","spire"],
    anchor: [6,10,-4],
    cells: [
      { dx: -10, dy: 0, dz: 0, blockId: 'chrome', layer: 10 },
      { dx: -10, dy: 0, dz: 4, blockId: 'chrome', layer: 10 },
      { dx: -10, dy: 0, dz: 8, blockId: 'chrome', layer: 10 },
      { dx: -8, dy: 0, dz: 8, blockId: 'chrome', layer: 10 },
      { dx: -6, dy: 0, dz: 8, blockId: 'chrome', layer: 10 },
      { dx: -4, dy: 0, dz: 8, blockId: 'chrome', layer: 10 },
      { dx: -2, dy: 0, dz: 1, blockId: 'chrome', layer: 10 },
      { dx: -2, dy: 0, dz: 5, blockId: 'chrome', layer: 10 },
      { dx: -10, dy: 1, dz: 0, blockId: 'neon-cyan', layer: 11 },
      { dx: -10, dy: 1, dz: 4, blockId: 'neon-cyan', layer: 11 },
      { dx: -10, dy: 1, dz: 8, blockId: 'neon-cyan', layer: 11 },
      { dx: -9, dy: 1, dz: 3, blockId: 'neon-cyan', layer: 11 },
      { dx: -9, dy: 1, dz: 7, blockId: 'neon-cyan', layer: 11 },
      { dx: -8, dy: 1, dz: 2, blockId: 'neon-cyan', layer: 11 },
      { dx: -8, dy: 1, dz: 6, blockId: 'neon-cyan', layer: 11 },
      { dx: -7, dy: 1, dz: 1, blockId: 'neon-cyan', layer: 11 },
      { dx: -7, dy: 1, dz: 5, blockId: 'neon-cyan', layer: 11 },
      { dx: -6, dy: 1, dz: 0, blockId: 'neon-cyan', layer: 11 },
      { dx: -6, dy: 1, dz: 4, blockId: 'neon-cyan', layer: 11 },
      { dx: -6, dy: 1, dz: 8, blockId: 'neon-cyan', layer: 11 },
      { dx: -5, dy: 1, dz: 3, blockId: 'neon-cyan', layer: 11 },
      { dx: -5, dy: 1, dz: 7, blockId: 'neon-cyan', layer: 11 },
      { dx: -4, dy: 1, dz: 2, blockId: 'neon-cyan', layer: 11 },
      { dx: -4, dy: 1, dz: 6, blockId: 'neon-cyan', layer: 11 },
      { dx: -3, dy: 1, dz: 1, blockId: 'neon-cyan', layer: 11 },
      { dx: -3, dy: 1, dz: 5, blockId: 'neon-cyan', layer: 11 },
      { dx: -2, dy: 1, dz: 0, blockId: 'neon-cyan', layer: 11 },
      { dx: -2, dy: 1, dz: 4, blockId: 'neon-cyan', layer: 11 },
      { dx: -2, dy: 1, dz: 8, blockId: 'neon-cyan', layer: 11 },
      { dx: -7, dy: 0, dz: -8, blockId: 'holo-billboard', layer: 10 },
      { dx: 10, dy: 0, dz: -2, blockId: 'data-stream', layer: 10 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_cathedral_arch',
    name: 'Cathedral Arch',
    type: 'prefab',
    tags: ["arch","glitch"],
    anchor: [4,0,0],
    cells: [
      { dx: -2, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 6, dz: 0, blockId: 'glitch', layer: 6 },
      { dx: 1, dy: 8, dz: 0, blockId: 'glitch', layer: 8 },
      { dx: 0, dy: 10, dz: 0, blockId: 'glitch', layer: 10 },
      { dx: 2, dy: 9, dz: -2, blockId: 'glitch', layer: 9 },
      { dx: -1, dy: 0, dz: 0, blockId: 'power-line', layer: 0 },
      { dx: 1, dy: 0, dz: 0, blockId: 'power-line', layer: 0 },
      { dx: -2, dy: 0, dz: 0, blockId: 'power-line', layer: 0 },
      { dx: 0, dy: 0, dz: 0, blockId: 'power-line', layer: 0 },
      { dx: 1, dy: 0, dz: 1, blockId: 'power-line', layer: 0 },
      { dx: -2, dy: 0, dz: 0, blockId: 'power-line', layer: 0 },
      { dx: 0, dy: 0, dz: 0, blockId: 'power-line', layer: 0 },
      { dx: 1, dy: 0, dz: -1, blockId: 'power-line', layer: 0 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_cathedral_foundation',
    name: 'Cathedral Foundation',
    type: 'prefab',
    tags: ["arch","structure"],
    anchor: [2,0,-3],
    cells: [
      { dx: -3, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: -3, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: -3, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: -3, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 3, blockId: 'power-line', layer: 0 },
      { dx: 1, dy: 0, dz: 3, blockId: 'power-line', layer: 0 },
      { dx: 3, dy: 0, dz: 3, blockId: 'power-line', layer: 0 },
      { dx: -1, dy: 0, dz: 3, blockId: 'power-line', layer: 0 },
      { dx: 1, dy: 0, dz: 3, blockId: 'power-line', layer: 0 },
      { dx: 3, dy: 0, dz: 3, blockId: 'power-line', layer: 0 },
      { dx: -3, dy: 0, dz: 3, blockId: 'power-line', layer: 0 },
      { dx: -3, dy: 0, dz: 3, blockId: 'power-line', layer: 0 },
      { dx: -3, dy: 0, dz: 3, blockId: 'power-line', layer: 0 },
      { dx: -1, dy: 0, dz: 3, blockId: 'power-line', layer: 0 },
      { dx: 1, dy: 0, dz: 3, blockId: 'power-line', layer: 0 },
      { dx: 3, dy: 0, dz: 3, blockId: 'power-line', layer: 0 },
      { dx: 3, dy: 0, dz: 1, blockId: 'power-line', layer: 0 },
      { dx: 3, dy: 0, dz: -1, blockId: 'power-line', layer: 0 },
      { dx: 3, dy: 0, dz: -3, blockId: 'power-line', layer: 0 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_cathedral_neon_sigil',
    name: 'Cathedral Neon Sigil',
    type: 'prefab',
    tags: ["arch","neon","glitch"],
    anchor: [-4,5,-3],
    cells: [
      { dx: -3, dy: 0, dz: 3, blockId: 'circuit', layer: 5 },
      { dx: -2, dy: 1, dz: 3, blockId: 'glitch', layer: 6 },
      { dx: -2, dy: 2, dz: 3, blockId: 'circuit', layer: 7 },
      { dx: -1, dy: 3, dz: 3, blockId: 'glitch', layer: 8 },
      { dx: 0, dy: 0, dz: -3, blockId: 'circuit', layer: 5 },
      { dx: 1, dy: 1, dz: -2, blockId: 'glitch', layer: 6 },
      { dx: 1, dy: 2, dz: -2, blockId: 'circuit', layer: 7 },
      { dx: 1, dy: 3, dz: -1, blockId: 'glitch', layer: 8 },
      { dx: 0, dy: 3, dz: -2, blockId: 'glitch', layer: 8 },
      { dx: -1, dy: 3, dz: -2, blockId: 'glitch', layer: 8 },
      { dx: 3, dy: 3, dz: -3, blockId: 'holo-billboard', layer: 8 },
      { dx: -2, dy: 3, dz: 2, blockId: 'holo-billboard', layer: 8 },
      { dx: -3, dy: 3, dz: -1, blockId: 'holo-billboard', layer: 8 },
      { dx: 0, dy: 3, dz: -2, blockId: 'holo-billboard', layer: 8 },
      { dx: 2, dy: 0, dz: -1, blockId: 'neon-magenta', layer: 5 },
      { dx: 3, dy: 0, dz: -1, blockId: 'neon-magenta', layer: 5 },
      { dx: 1, dy: 0, dz: -1, blockId: 'neon-magenta', layer: 5 },
      { dx: 2, dy: 0, dz: 0, blockId: 'neon-magenta', layer: 5 },
      { dx: 2, dy: 0, dz: -2, blockId: 'neon-magenta', layer: 5 },
      { dx: 1, dy: 0, dz: 0, blockId: 'neon-magenta', layer: 5 },
      { dx: 2, dy: 0, dz: 0, blockId: 'neon-magenta', layer: 5 },
      { dx: 0, dy: 0, dz: 0, blockId: 'neon-magenta', layer: 5 },
      { dx: 1, dy: 0, dz: 1, blockId: 'neon-magenta', layer: 5 },
      { dx: 1, dy: 0, dz: -1, blockId: 'neon-magenta', layer: 5 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_cathedral_spire',
    name: 'Cathedral Spire',
    type: 'prefab',
    tags: ["arch","glitch","data","neon","spire"],
    anchor: [-1,10,1],
    cells: [
      { dx: 5, dy: 0, dz: -1, blockId: 'glitch', layer: 10 },
      { dx: 5, dy: 1, dz: -1, blockId: 'neural-node', layer: 11 },
      { dx: 3, dy: 0, dz: 3, blockId: 'glitch', layer: 10 },
      { dx: 3, dy: 1, dz: 3, blockId: 'neural-node', layer: 11 },
      { dx: -1, dy: 0, dz: 3, blockId: 'glitch', layer: 10 },
      { dx: -1, dy: 1, dz: 3, blockId: 'neural-node', layer: 11 },
      { dx: -3, dy: 0, dz: -1, blockId: 'glitch', layer: 10 },
      { dx: -3, dy: 1, dz: -1, blockId: 'neural-node', layer: 11 },
      { dx: -1, dy: 0, dz: -5, blockId: 'glitch', layer: 10 },
      { dx: -1, dy: 1, dz: -5, blockId: 'neural-node', layer: 11 },
      { dx: 3, dy: 0, dz: -5, blockId: 'glitch', layer: 10 },
      { dx: 3, dy: 1, dz: -5, blockId: 'neural-node', layer: 11 },
      { dx: -7, dy: 0, dz: 0, blockId: 'data-stream', layer: 10 },
      { dx: 0, dy: 0, dz: -7, blockId: 'glitch', layer: 10 },
      { dx: -8, dy: 0, dz: 1, blockId: 'glitch', layer: 10 },
      { dx: 0, dy: 0, dz: 8, blockId: 'holo-billboard', layer: 10 },
      { dx: -6, dy: 0, dz: 3, blockId: 'data-stream', layer: 10 },
      { dx: -5, dy: 0, dz: -5, blockId: 'holo-billboard', layer: 10 },
      { dx: 2, dy: 0, dz: -10, blockId: 'glitch', layer: 10 },
      { dx: -4, dy: 0, dz: -5, blockId: 'glitch', layer: 10 },
      { dx: -6, dy: 0, dz: -6, blockId: 'glitch', layer: 10 },
      { dx: 6, dy: 0, dz: 3, blockId: 'holo-billboard', layer: 10 },
      { dx: 3, dy: 0, dz: 9, blockId: 'glitch', layer: 10 },
      { dx: 5, dy: 0, dz: 4, blockId: 'data-stream', layer: 10 },
      { dx: -5, dy: 0, dz: -1, blockId: 'holo-billboard', layer: 10 },
      { dx: -2, dy: 0, dz: -9, blockId: 'data-stream', layer: 10 },
      { dx: 0, dy: 0, dz: 8, blockId: 'glitch', layer: 10 },
      { dx: 6, dy: 0, dz: 5, blockId: 'holo-billboard', layer: 10 },
      { dx: -2, dy: 0, dz: 4, blockId: 'glitch', layer: 10 },
      { dx: -3, dy: 0, dz: 5, blockId: 'data-stream', layer: 10 },
      { dx: -3, dy: 0, dz: 8, blockId: 'data-stream', layer: 10 },
      { dx: -3, dy: 0, dz: 5, blockId: 'holo-billboard', layer: 10 },
      { dx: -1, dy: 0, dz: 8, blockId: 'data-stream', layer: 10 },
      { dx: 8, dy: 0, dz: -4, blockId: 'data-stream', layer: 10 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_data_tower_segment',
    name: 'Data Tower Segment',
    type: 'prefab',
    tags: ["structure","neon","glitch","data"],
    anchor: [-3,0,1],
    cells: [
      { dx: -2, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 0, blockId: 'circuit', layer: 0 },
      { dx: 1, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 1, dz: 0, blockId: 'chrome', layer: 1 },
      { dx: -1, dy: 2, dz: -2, blockId: 'chrome', layer: 2 },
      { dx: -1, dy: 2, dz: 1, blockId: 'chrome', layer: 2 },
      { dx: -1, dy: 3, dz: -1, blockId: 'chrome', layer: 3 },
      { dx: -1, dy: 3, dz: 2, blockId: 'chrome', layer: 3 },
      { dx: -1, dy: 4, dz: 0, blockId: 'neon-cyan', layer: 4 },
      { dx: -1, dy: 5, dz: -2, blockId: 'chrome', layer: 5 },
      { dx: -1, dy: 5, dz: 1, blockId: 'chrome', layer: 5 },
      { dx: -1, dy: 6, dz: -1, blockId: 'chrome', layer: 6 },
      { dx: -1, dy: 6, dz: 2, blockId: 'chrome', layer: 6 },
      { dx: -1, dy: 7, dz: 0, blockId: 'chrome', layer: 7 },
      { dx: -1, dy: 8, dz: -2, blockId: 'neon-cyan', layer: 8 },
      { dx: -1, dy: 8, dz: 1, blockId: 'neon-cyan', layer: 8 },
      { dx: -1, dy: 9, dz: -1, blockId: 'chrome', layer: 9 },
      { dx: -1, dy: 9, dz: 2, blockId: 'chrome', layer: 9 },
      { dx: -1, dy: 10, dz: 0, blockId: 'chrome', layer: 10 },
      { dx: -1, dy: 11, dz: -2, blockId: 'neon-cyan', layer: 11 },
      { dx: -1, dy: 11, dz: 1, blockId: 'neon-cyan', layer: 11 },
      { dx: 0, dy: 11, dz: -1, blockId: 'neon-cyan', layer: 11 },
      { dx: 0, dy: 11, dz: 2, blockId: 'neon-cyan', layer: 11 },
      { dx: 1, dy: 11, dz: 0, blockId: 'neon-cyan', layer: 11 },
      { dx: 2, dy: 11, dz: -2, blockId: 'neon-cyan', layer: 11 },
      { dx: 2, dy: 11, dz: 1, blockId: 'neon-cyan', layer: 11 },
      { dx: 0, dy: 8, dz: -2, blockId: 'data-stream', layer: 8 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_glitch_apex',
    name: 'Glitch Apex',
    type: 'prefab',
    tags: ["glitch","data","energy","spire"],
    anchor: [0,10,-1],
    cells: [
      { dx: 1, dy: 0, dz: 5, blockId: 'toxic-core', layer: 10 },
      { dx: 9, dy: 0, dz: 2, blockId: 'glitch', layer: 10 },
      { dx: 9, dy: 1, dz: 2, blockId: 'toxic-core', layer: 11 },
      { dx: 0, dy: 0, dz: 4, blockId: 'toxic-core', layer: 10 },
      { dx: 8, dy: 0, dz: 5, blockId: 'toxic-core', layer: 10 },
      { dx: -10, dy: 0, dz: 6, blockId: 'glitch', layer: 10 },
      { dx: -10, dy: 1, dz: 6, blockId: 'toxic-core', layer: 11 },
      { dx: -6, dy: 0, dz: 2, blockId: 'toxic-core', layer: 10 },
      { dx: 4, dy: 0, dz: 8, blockId: 'neural-node', layer: 10 },
      { dx: -2, dy: 0, dz: 7, blockId: 'neural-node', layer: 10 },
      { dx: -5, dy: 0, dz: -7, blockId: 'data-stream', layer: 10 },
      { dx: -2, dy: 0, dz: -9, blockId: 'data-stream', layer: 10 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_glitch_core',
    name: 'Glitch Core',
    type: 'prefab',
    tags: ["glitch","data"],
    anchor: [-8,5,3],
    cells: [
      { dx: 2, dy: 0, dz: 0, blockId: 'circuit', layer: 5 },
      { dx: 2, dy: 1, dz: 0, blockId: 'glitch', layer: 6 },
      { dx: 2, dy: 2, dz: 0, blockId: 'circuit', layer: 7 },
      { dx: 2, dy: 3, dz: 0, blockId: 'circuit', layer: 8 },
      { dx: 0, dy: 0, dz: 1, blockId: 'glitch', layer: 5 },
      { dx: 0, dy: 1, dz: 1, blockId: 'glitch', layer: 6 },
      { dx: 0, dy: 2, dz: 1, blockId: 'glitch', layer: 7 },
      { dx: 0, dy: 3, dz: 1, blockId: 'glitch', layer: 8 },
      { dx: -2, dy: 0, dz: 2, blockId: 'circuit', layer: 5 },
      { dx: -2, dy: 1, dz: 2, blockId: 'circuit', layer: 6 },
      { dx: -2, dy: 2, dz: 2, blockId: 'glitch', layer: 7 },
      { dx: -2, dy: 3, dz: 2, blockId: 'circuit', layer: 8 },
      { dx: 2, dy: 0, dz: -2, blockId: 'glitch', layer: 5 },
      { dx: 2, dy: 1, dz: -2, blockId: 'glitch', layer: 6 },
      { dx: 2, dy: 2, dz: -2, blockId: 'circuit', layer: 7 },
      { dx: 2, dy: 3, dz: -2, blockId: 'glitch', layer: 8 },
      { dx: 1, dy: 3, dz: -1, blockId: 'neural-node', layer: 8 },
      { dx: 3, dy: 1, dz: -1, blockId: 'data-stream', layer: 6 },
      { dx: -3, dy: 2, dz: 1, blockId: 'data-stream', layer: 7 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_glitch_ground',
    name: 'Glitch Ground',
    type: 'prefab',
    tags: ["glitch","structure"],
    anchor: [1,0,3],
    cells: [
      { dx: -3, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: -3, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: -3, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: -3, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_glitch_tower',
    name: 'Glitch Tower',
    type: 'prefab',
    tags: ["glitch","energy"],
    anchor: [9,0,1],
    cells: [
      { dx: -2, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 1, dz: 0, blockId: 'glitch', layer: 1 },
      { dx: 0, dy: 2, dz: 0, blockId: 'glitch', layer: 2 },
      { dx: 0, dy: 3, dz: 0, blockId: 'glitch', layer: 3 },
      { dx: 0, dy: 4, dz: 0, blockId: 'glitch', layer: 4 },
      { dx: 0, dy: 5, dz: 0, blockId: 'circuit', layer: 5 },
      { dx: 0, dy: 6, dz: 0, blockId: 'circuit', layer: 6 },
      { dx: 0, dy: 7, dz: 0, blockId: 'circuit', layer: 7 },
      { dx: 0, dy: 8, dz: 0, blockId: 'circuit', layer: 8 },
      { dx: 0, dy: 9, dz: 0, blockId: 'glitch', layer: 9 },
      { dx: 0, dy: 10, dz: 0, blockId: 'glitch', layer: 10 },
      { dx: 0, dy: 11, dz: 0, blockId: 'toxic-core', layer: 11 },
      { dx: 0, dy: 1, dz: -2, blockId: 'glitch', layer: 1 },
      { dx: 0, dy: 2, dz: -2, blockId: 'glitch', layer: 2 },
      { dx: -1, dy: 1, dz: 0, blockId: 'glitch', layer: 1 },
      { dx: -1, dy: 2, dz: 0, blockId: 'circuit', layer: 2 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_megaspire_base',
    name: 'Megaspire Base',
    type: 'prefab',
    tags: ["spire","structure"],
    anchor: [-5,0,-5],
    cells: [
      { dx: -3, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: -3, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: -3, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: -3, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: -3, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 3, dy: 0, dz: 3, blockId: 'obsidian', layer: 0 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_megaspire_crown',
    name: 'Megaspire Crown',
    type: 'prefab',
    tags: ["spire","structure","data"],
    anchor: [-1,10,-1],
    cells: [
      { dx: -2, dy: 0, dz: -2, blockId: 'corp-glass', layer: 10 },
      { dx: -2, dy: 0, dz: 0, blockId: 'corp-glass', layer: 10 },
      { dx: -2, dy: 0, dz: 2, blockId: 'corp-glass', layer: 10 },
      { dx: -2, dy: 0, dz: 4, blockId: 'corp-glass', layer: 10 },
      { dx: -1, dy: 0, dz: 4, blockId: 'corp-glass', layer: 10 },
      { dx: 0, dy: 0, dz: 4, blockId: 'corp-glass', layer: 10 },
      { dx: 1, dy: 0, dz: 4, blockId: 'corp-glass', layer: 10 },
      { dx: 2, dy: 0, dz: 4, blockId: 'corp-glass', layer: 10 },
      { dx: 3, dy: 0, dz: 4, blockId: 'corp-glass', layer: 10 },
      { dx: 4, dy: 0, dz: -1, blockId: 'corp-glass', layer: 10 },
      { dx: 4, dy: 0, dz: 1, blockId: 'corp-glass', layer: 10 },
      { dx: 4, dy: 0, dz: 3, blockId: 'corp-glass', layer: 10 },
      { dx: 1, dy: 0, dz: 1, blockId: 'power-line', layer: 10 },
      { dx: -1, dy: 1, dz: 0, blockId: 'chrome', layer: 11 },
      { dx: -1, dy: 1, dz: 2, blockId: 'chrome', layer: 11 },
      { dx: 0, dy: 1, dz: -1, blockId: 'chrome', layer: 11 },
      { dx: 0, dy: 1, dz: 1, blockId: 'chrome', layer: 11 },
      { dx: 0, dy: 1, dz: 3, blockId: 'chrome', layer: 11 },
      { dx: 1, dy: 1, dz: 0, blockId: 'chrome', layer: 11 },
      { dx: 1, dy: 1, dz: 2, blockId: 'chrome', layer: 11 },
      { dx: 2, dy: 1, dz: -1, blockId: 'chrome', layer: 11 },
      { dx: 2, dy: 1, dz: 1, blockId: 'chrome', layer: 11 },
      { dx: 2, dy: 1, dz: 3, blockId: 'chrome', layer: 11 },
      { dx: 3, dy: 1, dz: 0, blockId: 'chrome', layer: 11 },
      { dx: 3, dy: 1, dz: 2, blockId: 'chrome', layer: 11 },
      { dx: 1, dy: 1, dz: 1, blockId: 'neural-node', layer: 11 },
      { dx: -3, dy: 0, dz: -4, blockId: 'data-stream', layer: 10 },
      { dx: 1, dy: 0, dz: 1, blockId: 'data-stream', layer: 10 },
      { dx: -5, dy: 0, dz: -3, blockId: 'data-stream', layer: 10 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_megaspire_cyan_band',
    name: 'Megaspire Cyan Band',
    type: 'prefab',
    tags: ["spire","structure","neon","data"],
    anchor: [0,5,0],
    cells: [
      { dx: -3, dy: 0, dz: -3, blockId: 'corp-glass', layer: 5 },
      { dx: -3, dy: 0, dz: 0, blockId: 'corp-glass', layer: 5 },
      { dx: -3, dy: 0, dz: 3, blockId: 'corp-glass', layer: 5 },
      { dx: -1, dy: 0, dz: -3, blockId: 'corp-glass', layer: 5 },
      { dx: 0, dy: 0, dz: 3, blockId: 'corp-glass', layer: 5 },
      { dx: 2, dy: 0, dz: -3, blockId: 'corp-glass', layer: 5 },
      { dx: 3, dy: 0, dz: -2, blockId: 'corp-glass', layer: 5 },
      { dx: 3, dy: 0, dz: 1, blockId: 'corp-glass', layer: 5 },
      { dx: 0, dy: 0, dz: 0, blockId: 'power-line', layer: 5 },
      { dx: -3, dy: 1, dz: -1, blockId: 'neon-cyan', layer: 6 },
      { dx: -3, dy: 1, dz: 2, blockId: 'neon-cyan', layer: 6 },
      { dx: -2, dy: 1, dz: 3, blockId: 'neon-cyan', layer: 6 },
      { dx: 0, dy: 1, dz: -3, blockId: 'neon-cyan', layer: 6 },
      { dx: 1, dy: 1, dz: 3, blockId: 'neon-cyan', layer: 6 },
      { dx: 3, dy: 1, dz: -3, blockId: 'neon-cyan', layer: 6 },
      { dx: 3, dy: 1, dz: 0, blockId: 'neon-cyan', layer: 6 },
      { dx: 3, dy: 1, dz: 3, blockId: 'neon-cyan', layer: 6 },
      { dx: -3, dy: 2, dz: -2, blockId: 'corp-glass', layer: 7 },
      { dx: -3, dy: 2, dz: 1, blockId: 'corp-glass', layer: 7 },
      { dx: -2, dy: 2, dz: -3, blockId: 'corp-glass', layer: 7 },
      { dx: -1, dy: 2, dz: 3, blockId: 'corp-glass', layer: 7 },
      { dx: 1, dy: 2, dz: -3, blockId: 'corp-glass', layer: 7 },
      { dx: 2, dy: 2, dz: 3, blockId: 'corp-glass', layer: 7 },
      { dx: 3, dy: 2, dz: -1, blockId: 'corp-glass', layer: 7 },
      { dx: 3, dy: 2, dz: 2, blockId: 'corp-glass', layer: 7 },
      { dx: -3, dy: 3, dz: -3, blockId: 'corp-glass', layer: 8 },
      { dx: -3, dy: 3, dz: 0, blockId: 'corp-glass', layer: 8 },
      { dx: -3, dy: 3, dz: 3, blockId: 'corp-glass', layer: 8 },
      { dx: -1, dy: 3, dz: -3, blockId: 'corp-glass', layer: 8 },
      { dx: 0, dy: 3, dz: 3, blockId: 'corp-glass', layer: 8 },
      { dx: 2, dy: 3, dz: -3, blockId: 'corp-glass', layer: 8 },
      { dx: 3, dy: 3, dz: -2, blockId: 'corp-glass', layer: 8 },
      { dx: 3, dy: 3, dz: 1, blockId: 'corp-glass', layer: 8 },
      { dx: 0, dy: 3, dz: 0, blockId: 'power-line', layer: 8 },
      { dx: -3, dy: 3, dz: 0, blockId: 'data-stream', layer: 8 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_megaspire_glass_ring',
    name: 'Megaspire Glass Ring',
    type: 'prefab',
    tags: ["spire","structure","data"],
    anchor: [0,0,0],
    cells: [
      { dx: -2, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: -2, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: -1, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: -1, blockId: 'obsidian', layer: 0 },
      { dx: 1, dy: 0, dz: 1, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: -2, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: 0, blockId: 'obsidian', layer: 0 },
      { dx: 2, dy: 0, dz: 2, blockId: 'obsidian', layer: 0 },
      { dx: 0, dy: 2, dz: 0, blockId: 'power-line', layer: 2 },
      { dx: 0, dy: 4, dz: 0, blockId: 'power-line', layer: 4 },
      { dx: 0, dy: 6, dz: 0, blockId: 'power-line', layer: 6 },
      { dx: 0, dy: 8, dz: 0, blockId: 'power-line', layer: 8 },
      { dx: 0, dy: 10, dz: 0, blockId: 'power-line', layer: 10 },
      { dx: -2, dy: 11, dz: -1, blockId: 'chrome', layer: 11 },
      { dx: -2, dy: 11, dz: 1, blockId: 'chrome', layer: 11 },
      { dx: -1, dy: 11, dz: -2, blockId: 'chrome', layer: 11 },
      { dx: -1, dy: 11, dz: 0, blockId: 'chrome', layer: 11 },
      { dx: -1, dy: 11, dz: 2, blockId: 'chrome', layer: 11 },
      { dx: 0, dy: 11, dz: -1, blockId: 'chrome', layer: 11 },
      { dx: 0, dy: 11, dz: 1, blockId: 'chrome', layer: 11 },
      { dx: 1, dy: 11, dz: -2, blockId: 'chrome', layer: 11 },
      { dx: 1, dy: 11, dz: 0, blockId: 'chrome', layer: 11 },
      { dx: 1, dy: 11, dz: 2, blockId: 'chrome', layer: 11 },
      { dx: 2, dy: 11, dz: -1, blockId: 'chrome', layer: 11 },
      { dx: 2, dy: 11, dz: 1, blockId: 'chrome', layer: 11 },
      { dx: 0, dy: 11, dz: 0, blockId: 'neural-node', layer: 11 },
      { dx: -1, dy: 2, dz: -2, blockId: 'data-stream', layer: 2 },
      { dx: -1, dy: 6, dz: -2, blockId: 'data-stream', layer: 6 },
      { dx: 0, dy: 10, dz: 0, blockId: 'data-stream', layer: 10 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_shrine_altar',
    name: 'Shrine Altar',
    type: 'prefab',
    tags: ["shrine","data","energy","neon"],
    anchor: [0,0,0],
    cells: [
      { dx: -2, dy: 0, dz: -2, blockId: 'chrome', layer: 0 },
      { dx: -2, dy: 0, dz: 0, blockId: 'chrome', layer: 0 },
      { dx: -2, dy: 0, dz: 2, blockId: 'chrome', layer: 0 },
      { dx: -1, dy: 0, dz: -1, blockId: 'chrome', layer: 0 },
      { dx: -1, dy: 0, dz: 1, blockId: 'chrome', layer: 0 },
      { dx: 0, dy: 0, dz: -2, blockId: 'chrome', layer: 0 },
      { dx: 0, dy: 0, dz: 0, blockId: 'chrome', layer: 0 },
      { dx: 0, dy: 0, dz: 2, blockId: 'chrome', layer: 0 },
      { dx: 1, dy: 0, dz: -1, blockId: 'chrome', layer: 0 },
      { dx: 1, dy: 0, dz: 1, blockId: 'chrome', layer: 0 },
      { dx: 2, dy: 0, dz: -2, blockId: 'chrome', layer: 0 },
      { dx: 2, dy: 0, dz: 0, blockId: 'chrome', layer: 0 },
      { dx: 2, dy: 0, dz: 2, blockId: 'chrome', layer: 0 },
      { dx: 0, dy: 2, dz: 0, blockId: 'neural-node', layer: 2 },
      { dx: 0, dy: 4, dz: 0, blockId: 'toxic-core', layer: 4 },
      { dx: -1, dy: 9, dz: -2, blockId: 'holo-billboard', layer: 9 },
      { dx: -2, dy: 1, dz: 0, blockId: 'power-line', layer: 1 },
      { dx: -2, dy: 3, dz: 0, blockId: 'power-line', layer: 3 },
      { dx: -2, dy: 5, dz: 0, blockId: 'power-line', layer: 5 },
      { dx: 2, dy: 2, dz: 0, blockId: 'power-line', layer: 2 },
      { dx: 2, dy: 4, dz: 0, blockId: 'power-line', layer: 4 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_shrine_crown',
    name: 'Shrine Crown',
    type: 'prefab',
    tags: ["shrine","neon","spire"],
    anchor: [0,9,1],
    cells: [
      { dx: 1, dy: 0, dz: 0, blockId: 'holo-billboard', layer: 9 },
      { dx: -3, dy: 0, dz: 2, blockId: 'holo-billboard', layer: 9 },
      { dx: 3, dy: 0, dz: 0, blockId: 'holo-billboard', layer: 9 },
      { dx: -3, dy: 1, dz: -3, blockId: 'holo-billboard', layer: 10 },
      { dx: -1, dy: 0, dz: -3, blockId: 'holo-billboard', layer: 9 },
      { dx: 0, dy: 0, dz: -1, blockId: 'holo-billboard', layer: 9 },
      { dx: -3, dy: 0, dz: 1, blockId: 'holo-billboard', layer: 9 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_shrine_foundation',
    name: 'Shrine Foundation',
    type: 'prefab',
    tags: ["shrine","structure"],
    anchor: [0,0,0],
    cells: [
      { dx: -3, dy: 0, dz: -3, blockId: 'chrome', layer: 0 },
      { dx: -3, dy: 0, dz: -1, blockId: 'chrome', layer: 0 },
      { dx: -3, dy: 0, dz: 1, blockId: 'chrome', layer: 0 },
      { dx: -3, dy: 0, dz: 3, blockId: 'chrome', layer: 0 },
      { dx: -2, dy: 0, dz: -2, blockId: 'chrome', layer: 0 },
      { dx: -2, dy: 0, dz: 0, blockId: 'chrome', layer: 0 },
      { dx: -2, dy: 0, dz: 2, blockId: 'chrome', layer: 0 },
      { dx: -1, dy: 0, dz: -3, blockId: 'chrome', layer: 0 },
      { dx: -1, dy: 0, dz: -1, blockId: 'chrome', layer: 0 },
      { dx: -1, dy: 0, dz: 1, blockId: 'chrome', layer: 0 },
      { dx: -1, dy: 0, dz: 3, blockId: 'chrome', layer: 0 },
      { dx: 0, dy: 0, dz: -2, blockId: 'chrome', layer: 0 },
      { dx: 0, dy: 0, dz: 0, blockId: 'chrome', layer: 0 },
      { dx: 0, dy: 0, dz: 2, blockId: 'chrome', layer: 0 },
      { dx: 1, dy: 0, dz: -3, blockId: 'chrome', layer: 0 },
      { dx: 1, dy: 0, dz: -1, blockId: 'chrome', layer: 0 },
      { dx: 1, dy: 0, dz: 1, blockId: 'chrome', layer: 0 },
      { dx: 1, dy: 0, dz: 3, blockId: 'chrome', layer: 0 },
      { dx: 2, dy: 0, dz: -2, blockId: 'chrome', layer: 0 },
      { dx: 2, dy: 0, dz: 0, blockId: 'chrome', layer: 0 },
      { dx: 2, dy: 0, dz: 2, blockId: 'chrome', layer: 0 },
      { dx: 3, dy: 0, dz: -3, blockId: 'chrome', layer: 0 },
      { dx: 3, dy: 0, dz: -1, blockId: 'chrome', layer: 0 },
      { dx: 3, dy: 0, dz: 1, blockId: 'chrome', layer: 0 },
      { dx: 3, dy: 0, dz: 3, blockId: 'chrome', layer: 0 },
    ],
    createdAt: 0,
  },
  {
    id: 'prefab_shrine_neon_ring',
    name: 'Shrine Neon Ring',
    type: 'prefab',
    tags: ["shrine","neon","energy"],
    anchor: [0,4,0],
    cells: [
      { dx: -3, dy: 0, dz: -3, blockId: 'obsidian', layer: 4 },
      { dx: -3, dy: 2, dz: -3, blockId: 'obsidian', layer: 6 },
      { dx: 3, dy: 0, dz: -3, blockId: 'obsidian', layer: 4 },
      { dx: 3, dy: 2, dz: -3, blockId: 'obsidian', layer: 6 },
      { dx: -3, dy: 0, dz: 3, blockId: 'obsidian', layer: 4 },
      { dx: -3, dy: 2, dz: 3, blockId: 'obsidian', layer: 6 },
      { dx: 3, dy: 0, dz: 3, blockId: 'obsidian', layer: 4 },
      { dx: 3, dy: 2, dz: 3, blockId: 'obsidian', layer: 6 },
      { dx: -3, dy: 2, dz: -3, blockId: 'neon-magenta', layer: 6 },
      { dx: -2, dy: 2, dz: -3, blockId: 'neon-magenta', layer: 6 },
      { dx: -1, dy: 2, dz: -3, blockId: 'neon-magenta', layer: 6 },
      { dx: 0, dy: 2, dz: -3, blockId: 'neon-magenta', layer: 6 },
      { dx: 1, dy: 2, dz: -3, blockId: 'neon-magenta', layer: 6 },
      { dx: 2, dy: 2, dz: -3, blockId: 'neon-magenta', layer: 6 },
      { dx: 3, dy: 2, dz: -3, blockId: 'neon-magenta', layer: 6 },
      { dx: -3, dy: 2, dz: -3, blockId: 'neon-magenta', layer: 6 },
      { dx: -3, dy: 2, dz: -2, blockId: 'neon-magenta', layer: 6 },
      { dx: -3, dy: 2, dz: -1, blockId: 'neon-magenta', layer: 6 },
      { dx: -3, dy: 2, dz: 0, blockId: 'neon-magenta', layer: 6 },
      { dx: -3, dy: 2, dz: 1, blockId: 'neon-magenta', layer: 6 },
      { dx: -3, dy: 2, dz: 2, blockId: 'neon-magenta', layer: 6 },
      { dx: -3, dy: 2, dz: 3, blockId: 'neon-magenta', layer: 6 },
      { dx: 0, dy: 0, dz: 0, blockId: 'toxic-core', layer: 4 },
      { dx: -2, dy: 1, dz: 0, blockId: 'power-line', layer: 5 },
      { dx: 2, dy: 1, dz: 0, blockId: 'power-line', layer: 5 },
    ],
    createdAt: 0,
  }
];
